### ISSUE TITLE
Pull down the repo and set up the files on home computer

### ISSUE THREAD

**Issue by madhephaestus** [Allycat89/CustomComputerCase#1]
You should pull down the repository and get Eclipse, Git, OpenSCAD and FreeCAD working. Verify it is working by opening your 2 projects (one openscad one Freecad)

**Comment by Allycat89** [comment]
Dowloading and installing freecad. Also re-downloading eclipse since it was having an issue with my library not sure if some of it got deleted by windows in the past few months.

**Comment by Allycat89** [comment]
Alright got the repository and the projects was able to open scad and set up the java editor. I can open it with free cad as well though i have my computer still in Japanese for certain gaming so i will play with free cad another time.

**Comment by madhephaestus** [comment]
Ok, cool! Openscad is the much more powerful tool anyway.
